[book]
title = "LLM-Hosting"
authors = ["jstet"]
language = "en"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.bib]
bibliography = "bibliography.bib"
title = "Literaturverzeichnis"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
